/** Isolated browser fixture. Never imported by production or the dev API entrypoint.
 * Fake test identities, real disposable PostgreSQL, real server and browser code.
 */
import {InvitationService} from '../../server/multiplayer/invitations';
import {pgInvitations} from '../helpers/invitations';
import {createServer} from 'vite';
import {database,PgRepository} from '../helpers/postgres';
import {A,B,C,testers,creation} from '../helpers/remote';
import {MatchService} from '../../server/multiplayer/service';
import {createMatchHandler} from '../../server/multiplayer/routes';
import {ApiError} from '../../server/multiplayer/errors';
const db=await database();await db.pool.query('insert into auth.users(id) values($1),($2),($3)',[A,B,C]);
const community=creation().roster.you;community.name='Community Ace';await db.pool.query('insert into players(owner_id,id,name,appearance,skills,handedness,is_public) values($1,$2,$3,$4,$5,$6,true)',[B,community.id,community.name,community.appearance,community.skills,community.handedness]);
const service=new MatchService(new PgRepository(db.pool),testers);
const game=await service.create(A,creation());
const handler=createMatchHandler(service,async token=>{if([A,B,C].includes(token))return token;throw new ApiError(401,'authentication','Invalid fixture identity.');},undefined,new InvitationService(pgInvitations(new PgRepository(db.pool)),service,testers));
const server=await createServer({configFile:false,server:{host:'127.0.0.1',port:5177,strictPort:true},plugins:[{name:'isolated-remote-browser-fixture',enforce:'pre',resolveId(id){if(id.endsWith('/auth-session'))return '\0fixture-auth';},load(id){if(id==='\0fixture-auth')return `const owner=new URLSearchParams(location.search).get('viewer')==='b'?'${B}':'${A}';export const matchCredentials=async()=>({owner,token:owner});const call=async body=>fetch('/fixture-community',{method:'POST',headers:{'Content-Type':'application/json','x-fixture-owner':owner},body:JSON.stringify(body)}).then(r=>r.json());export const authClient=()=>({rpc:async(_name,args)=>call({action:'catalog',ids:args?.p_ids}),from:()=>{let action='',value={};const q={insert(v){action='add';value=v;return q},delete(){action='remove';return q},eq(k,v){value[k]=v;return q},then(resolve,reject){return call({action,...value}).then(resolve,reject)}};return q},auth:{getSession:async()=>({data:{session:{user:{id:owner,email:owner==='${A}'?'a@example.invalid':'b@example.invalid',user_metadata:{player_name:owner==='${A}'?'A':'B'}}}}}),signOut:async()=>({error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}});`;},configureServer(server){server.middlewares.use((req,res,next)=>{if(req.url==='/fixture-community'){void(async()=>{const owner=req.headers['x-fixture-owner'];if(owner!==A&&owner!==B){res.statusCode=403;res.end();return;}let raw='';for await(const chunk of req)raw+=chunk;const input=JSON.parse(raw),c=await db.pool.connect();try{await c.query('begin');await c.query('set local role authenticated');await c.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);let data:any[]=[];if(input.action==='catalog')data=(await c.query('select * from community_player_catalog($1)',[input.ids??null])).rows;else if(input.action==='add')await c.query('insert into community_player_selections(owner_id,public_id) values($1,$2) on conflict do nothing',[owner,input.public_id]);else if(input.action==='remove')await c.query('delete from community_player_selections where owner_id=$1 and public_id=$2',[owner,input.public_id]);await c.query('commit');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data,error:null}));}catch(e){await c.query('rollback');res.end(JSON.stringify({data:null,error:{message:String(e)}}));}finally{c.release();}})();return;}if(req.url?.startsWith('/api/invitations')||req.url?.startsWith('/api/matches')||req.url?.startsWith('/api/multiplayer'))void handler(req,res);else next();});}}]});
await server.listen();console.log(`Disposable remote UI fixture: http://127.0.0.1:5177/?multiplayer=1&match=${game.id} (A); add &viewer=b for B.`);
let closing=false;async function close(){if(closing)return;closing=true;await server.close();await db.close();process.exit(0);}process.on('SIGINT',()=>void close());process.on('SIGTERM',()=>void close());
