import test from 'node:test';import assert from 'node:assert/strict';
import {rivalryShareText,sendRivalryText,type RivalryShareMatch} from '../src/multiplayer/rivalry-share';
import type {RivalrySummary} from '../src/multiplayer/rivalry';
const id='11111111-1111-4111-8111-111111111111';
function match(won=true,away=false):RivalryShareMatch{const result={matchId:id,completedAt:'2026-09-18T00:00:00Z',result:won?'win' as const:'loss' as const,score:{you:won?3:1,opponent:won?1:3},rules:{target:3,winBy:1,scoring:'rally-doubles' as const}};const s:RivalrySummary={definitionVersion:1,games:1,wins:won?1:0,losses:won?0:1,streak:{owner:won?'you':'opponent',length:1},previousStreak:null,bestStreak:{you:won?1:0,opponent:won?0:1},recent:[result],closest:result,milestones:[]};return {id,status:'completed',viewerTeam:away?'away':'home',score:away?{home:result.score.opponent,away:result.score.you}:{home:result.score.you,away:result.score.opponent},rivalry:{current:s,atCompletion:s}};}
test('shares only explicit score and series facts with a clean public link',()=>{const m={...match(),strategy:{secret:'PRIVATE'},accountIds:{home:'ACCOUNT',away:'OTHER'}};const text=rivalryShareText(m,'Ryan','https://picklebash.app/path?secret=TOKEN');assert.equal(text,'I beat Ryan 3–1 in PickleBash. After this game, I led our series 1–0.\nPlay PickleBash:\nhttps://picklebash.app/?openplay=1');assert.doesNotMatch(text,/PRIVATE|ACCOUNT|TOKEN|11111111|strategy/);});
test('away orientation and losses use correct first-person score',()=>{assert.match(rivalryShareText(match(false,true),'Ryan','https://picklebash.app'),/^Ryan beat me 3–1.*After this game, Ryan led our series 1–0\./);});
test('game link is explicit, participant-only, and refers to the actual completed game',()=>{const text=rivalryShareText(match(),'Ryan','https://picklebash.app',true);assert.match(text,/players only/);const url=new URL(text.split('\n').at(-1)!);assert.equal(url.searchParams.get('match'),id);assert.equal(url.searchParams.get('openplay'),'1');});
test('rejects unfinished, abandoned, missing and contradictory history',()=>{for(const m of [{...match(),status:'active' as const},{...match(),endedEarly:true},{...match(),rivalry:undefined},{...match(),score:{home:3,away:2}}])assert.throws(()=>rivalryShareText(m,'Ryan','https://picklebash.app'));});
test('share uses exactly previewed text, cancellation never copies or reports success',async()=>{let copied=0;assert.equal(await sendRivalryText('exact message','share',{share:async data=>{assert.equal(data.text,'exact message');throw Object.assign(Error(),{name:'AbortError'});},copy:async()=>{copied++;}}),'cancelled');assert.equal(copied,0);assert.equal(await sendRivalryText('exact message','share',{share:async data=>{assert.equal(data.text,'exact message');},copy:async()=>{copied++;}}),'shared');assert.equal(copied,0);});
test('native fallback and explicit copy copy full message; failures remain failures',async()=>{let copied='';assert.equal(await sendRivalryText('score\nurl','share',{copy:async text=>{copied=text;}}),'copied');assert.equal(copied,'score\nurl');assert.equal(await sendRivalryText('copy','copy',{share:async()=>assert.fail(),copy:async text=>{copied=text;}}),'copied');await assert.rejects(sendRivalryText('x','share',{share:async()=>{throw Error('failed');},copy:async()=>assert.fail()}));});
