import {pressureMiddle} from '../src/scenarios/pressure-middle';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {COURT,Simulation,RALLY,sampleLeg} from '../src/simulation';
function advance(sim:Simulation){for(let i=0;i<10000&&sim.state.phase==='flight';i++)sim.update(1/60)}
test('regulation dimensions are exact, using international foot conversion',()=>{assert.equal(COURT.width,6.096);assert.equal(COURT.length,13.411200000000001);assert.equal(COURT.kitchen,2.1336);assert.equal(COURT.line,.0508);assert.equal(COURT.netCenter,.8635999999999999);assert.equal(COURT.netSideline,.9144)});
test('guided point pauses only at user contacts and awards one point after winner',()=>{const sim=new Simulation(pressureMiddle);assert.equal(sim.state.shotIndex,0);sim.submitIntent(sim.availableIntents[0]);advance(sim);assert.equal(sim.state.phase,'decision');assert.equal(sim.state.shotIndex,2);assert.equal(sim.state.bounces,2);assert.deepEqual(sim.state.ball.position,RALLY[2].contact);sim.submitIntent(sim.availableIntents[0]);advance(sim);assert.equal(sim.state.shotIndex,4);assert.equal(sim.state.phase,'decision');assert.equal(sim.state.bounces,2);assert.deepEqual(sim.state.ball.position,RALLY[4].contact);assert.ok(sim.state.players[0].position.z>COURT.kitchen);sim.submitIntent(sim.availableIntents[0]);advance(sim);assert.equal(sim.state.phase,'complete');assert.equal(sim.state.score.home,1);assert.deepEqual(sim.state.shotHistory.map(s=>s.type),['serve','return','drive','block','overhead']);sim.update(100);assert.equal(sim.state.score.home,1)});
test('pause freezes ball and players; reset clears all rally progress',()=>{const sim=new Simulation(pressureMiddle);sim.submitIntent(sim.availableIntents[0]);sim.update(.5);sim.state.paused=true;const state=structuredClone(sim.state);sim.update(10);assert.deepEqual(sim.state,state);sim.reset();assert.equal(sim.state.phase,'decision');assert.equal(sim.state.shotHistory.length,0);assert.equal(sim.state.bounces,0);assert.equal(sim.state.paused,false);assert.equal(sim.state.score.home,0)});
test('unsupported intents and duplicate submissions cannot mutate the rally',()=>{const sim=new Simulation(pressureMiddle);const before=structuredClone(sim.state);assert.throws(()=>sim.submitIntent({...sim.availableIntents[0],type:'lob'}));assert.throws(()=>sim.submitIntent({...sim.availableIntents[0],target:{x:NaN,y:0,z:0}}));assert.deepEqual(sim.state,before);const voice={...sim.availableIntents[0],source:'voice'};sim.submitIntent(voice);assert.equal(sim.state.shotHistory[0].source,'voice');assert.throws(()=>sim.submitIntent(voice));assert.throws(()=>sim.update(NaN))});
test('all scripted crossings clear the net and serve lands diagonally beyond kitchen',()=>{for(const shot of RALLY){for(const leg of shot.legs){if(leg.from.z*leg.to.z<0){const t=leg.from.z/(leg.from.z-leg.to.z);const ball=sampleLeg(leg,t);const net=COURT.netCenter+(COURT.netSideline-COURT.netCenter)*(ball.x/(COURT.width/2))**2;assert.ok(ball.y-.037>net,`${shot.title} clips net`)}}}const serve=RALLY[0];assert.ok(serve.contact.x*serve.aimPoint.x<0);assert.ok(serve.aimPoint.z < -COURT.kitchen);assert.ok(Math.abs(serve.aimPoint.z)<COURT.length/2);assert.ok(Math.abs(serve.aimPoint.x)<COURT.width/2)});
test('flight segments connect without teleporting and stop at decision for large delta',()=>{for(let i=0;i<RALLY.length;i++){const shot=RALLY[i];for(let j=1;j<shot.legs.length;j++)assert.deepEqual(shot.legs[j-1].to,shot.legs[j].from);if(i<RALLY.length-1)assert.deepEqual(shot.legs.at(-1)!.to,RALLY[i+1].contact)}const sim=new Simulation(pressureMiddle);sim.submitIntent(sim.availableIntents[0]);sim.update(100);assert.equal(sim.state.phase,'decision');assert.equal(sim.state.shotIndex,2)});
