import test from 'node:test';
import assert from 'node:assert/strict';
import {reduceStrategy} from '../server/multiplayer/strategy';
import {selectStrategyStory,loadStrategyStory} from '../server/multiplayer/strategy-story';
import {parseStrategyStory,strategyStoryCopy} from '../src/multiplayer/strategy-story';
import type {ShotMixRow} from '../server/multiplayer/shot-mix';
import type {MatchRepository} from '../server/multiplayer/repository';
function rows(count=8):ShotMixRow[]{return Array.from({length:count},(_,i)=>{const summary=reduceStrategy({revision:0,expected:0,events:[]},'a');for(const family of ['drop','drive'] as const){const m=summary.stages.third[family];m.eligible=10;m.selectedWhenEligible=(i<4)===(family==='drop')?9:1;m.selected=m.selectedWhenEligible;}return {id:`00000000-0000-4000-8000-${String(100-i).padStart(12,'0')}`,completed_at:new Date(Date.UTC(2026,8,20-i)).toISOString(),opponent_id:'b',engine_version:'one',rules:{scoring:'rally',target:3,winBy:1},athletes:{emma:'Emma',leo:'Leo'},summary};});}
test('strong shift produces one deterministic, traceable, owner-worded observation',()=>{const h=rows(),s=selectStrategyStory(h,h[0].id)!;assert.equal(s.key,'third-drive');assert.equal(s.direction,'less');assert.equal(s.recent.selected,4);assert.equal(s.previous.selected,36);assert.equal(s.recent.eligible,40);assert.deepEqual(selectStrategyStory([...h].reverse(),h[0].id),s);assert.deepEqual(parseStrategyStory(s),s);assert.doesNotMatch(strategyStoryCopy(s,'Ryan'),/because|caused|better|should|improv|won/i);});
test('low samples, missing history, noisy shifts and incompatible matches have no story',()=>{for(const mutate of [(h:ShotMixRow[])=>h.pop(),(h:ShotMixRow[])=>{h[1].summary=null;},(h:ShotMixRow[])=>{h[1].summary!.coverage.complete=false;},(h:ShotMixRow[])=>{h[1].engine_version='two';},(h:ShotMixRow[])=>{h[1].rules.target=11;},(h:ShotMixRow[])=>{h[1].athletes={other:'Other'};},(h:ShotMixRow[])=>{for(const r of h)for(const f of ['drop','drive'] as const){r.summary!.stages.third[f].eligible=2;r.summary!.stages.third[f].selectedWhenEligible=1;}},(h:ShotMixRow[])=>{for(const r of h)for(const f of ['drop','drive'] as const)r.summary!.stages.third[f].selectedWhenEligible=5;}]){const h=rows();mutate(h);assert.equal(selectStrategyStory(h,h[0].id),null);}});
test('a single unusual game cannot produce a story',()=>{const h=rows();for(const [i,r] of h.entries())for(const f of ['drop','drive'] as const){const m=r.summary!.stages.third[f];m.eligible=i===0?100:1;m.selectedWhenEligible=i===0?100:0;}assert.equal(selectStrategyStory(h,h[0].id),null);});
test('repeated same-direction candidate is suppressed across nearby completions',()=>{const h=rows(9);assert.ok(selectStrategyStory(h.slice(1),h[1].id));assert.equal(selectStrategyStory(h,h[0].id),null);});
test('rejects duplicate history, future head, malformed counts and extra private fields',()=>{const h=rows(),s=selectStrategyStory(h,h[0].id)!;assert.throws(()=>selectStrategyStory([...h,h[0]],h[0].id));assert.equal(selectStrategyStory(h,h[1].id),null);assert.throws(()=>parseStrategyStory({...s,seed:'secret'}));assert.throws(()=>parseStrategyStory({...s,recent:{...s.recent,selected:100}}));assert.throws(()=>parseStrategyStory({...s,percentagePointChange:2}));});
test('loader scopes to actor, opponent and completion time; rebuilds missing summaries',async()=>{const h=rows(),current=h[0],future={...h[0],id:'00000000-0000-4000-8000-999999999999',completed_at:'2026-09-21T00:00:00.000Z'},other={...h[1],id:'00000000-0000-4000-8000-888888888888',opponent_id:'c'};let reads=0;const repo={shotMixPage:async(actor:string,before:string)=>{assert.equal(actor,'a');assert.equal(before,current.completed_at);return [future,other,...h.map(r=>({...r,summary:null}))];},strategy:async(id:string,actor:string)=>{assert.equal(actor,'a');reads++;return h.find(r=>r.id===id)!.summary;}} as unknown as MatchRepository;const s=await loadStrategyStory(repo,'a',current.id,'b',current.completed_at);assert.ok(s);assert.equal(reads,8);assert.deepEqual(s,selectStrategyStory(h,current.id));});
test('service rejects unrelated readers before loading story data and leaves lists slim',async()=>{
 const {MemoryRepository,A,B,C,creation}=await import('./helpers/remote');const {MatchService}=await import('../server/multiplayer/service');
 const repo=new MemoryRepository(),service=new MatchService(repo,new Map([[A,'Alex'],[B,'Ryan']]));const game=await service.create(A,creation());const row=repo.rows.get(game.id)!;row.status='completed';row.completed_at=rows()[0].completed_at;
 let pages=0;Object.assign(repo,{strategy:async()=>rows()[0].summary,shotMixPage:async()=>{pages++;throw Error('temporarily unavailable');}});
 await assert.rejects(service.get(game.id,C));assert.equal(pages,0);
 const result=await service.get(game.id,A);assert.ok(result.strategy);assert.equal(result.strategyStory,undefined);assert.equal(pages,1);
 const list=await service.list(A);assert.equal(list[0].strategyStory,undefined);assert.equal(pages,1);
});
