import {matchCredentials} from './auth-session';
import {remoteRequest} from './multiplayer/api';
import {showViewDialog,focusView} from './view-focus';
import './account-safety.css';
export interface SafetyTarget {targetId?:string;publicId?:string;matchId?:string;messageId?:string}
export function openBlockedPlayers(){
 const dialog=document.createElement('dialog');dialog.className='account-safety-dialog';dialog.classList.add('ph-no-capture');dialog.setAttribute('aria-label','Blocked players');
 const loading=document.createElement('p');loading.textContent='Loading blocked players…';loading.setAttribute('role','status');
 const close=document.createElement('button');close.type='button';close.textContent='Close';close.onclick=()=>dialog.close();
 dialog.append(loading,close);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);showViewDialog(dialog);
 void blockedPlayersPanel().then(panel=>{if(dialog.isConnected)loading.replaceWith(panel);});
}
async function safety(path:string,input?:unknown){const c=await matchCredentials();return remoteRequest(c.token,'/api/multiplayer/safety/'+path,input);}
export function openPlayerSafety(target:SafetyTarget,name:string,onBlocked:()=>void=()=>{}){
 const dialog=document.createElement('dialog');dialog.className='account-safety-dialog';dialog.classList.add('ph-no-capture');dialog.setAttribute('aria-label',`Report or block ${name}`);
 const title=document.createElement('h2');title.textContent=`Report or block ${name}`;
 const copy=document.createElement('p');copy.textContent=(target.matchId?(target.messageId?'The selected message will be shared with the PickleBash team for review. ':'The last 10 messages from this opponent will be shared with the PickleBash team for review. '):'Reports are reviewed by the PickleBash team. ')+'Blocking hides this player and prevents new invitations, messages, and nudges between you.';
 const form=document.createElement('form'),label=document.createElement('label');label.textContent='Reason';const reason=document.createElement('select');for(const [id,text] of [['harassment','Harassment or bullying'],['inappropriate_content','Inappropriate content'],['impersonation','Impersonation'],['other','Other']]){const o=document.createElement('option');o.value=id;o.textContent=text;reason.append(o)}label.append(reason);
 const detailsLabel=document.createElement('label');detailsLabel.textContent='Details (optional)';const details=document.createElement('textarea');details.maxLength=500;detailsLabel.append(details);
 const status=document.createElement('p');status.setAttribute('role','status');const report=document.createElement('button');report.type='submit';report.textContent='Send report';form.append(label,detailsLabel,report);form.onsubmit=event=>{event.preventDefault();report.disabled=true;void safety('report',{...target,reason:reason.value,details:details.value}).then(()=>{status.textContent='Report received. Thank you for helping keep the court friendly.';details.value='';}).catch(e=>{status.textContent=e.message;}).finally(()=>{report.disabled=false;});};
 const block=document.createElement('button');block.type='button';block.textContent='Block player';block.onclick=()=>{block.disabled=true;void safety('block',{...target,blocked:true}).then(()=>{status.textContent='Player blocked.';onBlocked();}).catch(e=>{status.textContent=e.message;block.disabled=false;});};
 const close=document.createElement('button');close.type='button';close.textContent='Close';close.onclick=()=>dialog.close();dialog.append(title,copy,form,block,status,close);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);showViewDialog(dialog);focusView(dialog);
}
export function openAccountDeletion(guest=false){
 const dialog=document.createElement('dialog');dialog.className='account-safety-dialog';dialog.setAttribute('aria-label','Delete account');dialog.classList.add('ph-no-capture');
 const title=document.createElement('h2');title.textContent='Delete your account';const copy=document.createElement('p');copy.textContent='Request permanent deletion of your account, players, saved games, and shared designs. We will process your request within 30 days. Purchases will no longer be accessible through this account. Deletion does not refund purchases. Copies shared by other people and records required for payment disputes or safety may remain.';
 const form=document.createElement('form'),label=document.createElement('label');label.textContent='Confirm with your password';const password=document.createElement('input');password.type='password';password.autocomplete='current-password';password.required=true;password.maxLength=128;label.append(password);
 const confirmLabel=document.createElement('label');const confirm=document.createElement('input');confirm.type='checkbox';confirm.required=true;confirmLabel.append(confirm,document.createTextNode('I understand this permanently deletes my account.'));
 const status=document.createElement('p');status.setAttribute('role','status');const send=document.createElement('button');send.textContent='Request account deletion';if(!guest)form.append(label);else password.required=false;form.append(confirmLabel,send);form.onsubmit=e=>{e.preventDefault();send.disabled=true;void safety('delete-account',{confirmation:'DELETE',password:password.value}).then(()=>{password.value='';form.remove();status.textContent='Deletion requested. Your account and associated game data will be deleted within 30 days. Contact dzuy@automaticalabs.com if you need help.';}).catch(e=>{password.value='';status.textContent=e.message;send.disabled=false;});};
 const close=document.createElement('button');close.type='button';close.textContent='Cancel';close.onclick=()=>dialog.close();dialog.append(title,copy,form,status,close);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);showViewDialog(dialog);focusView(dialog);
}
export async function blockedPlayersPanel(){const panel=document.createElement('section');const title=document.createElement('h3');title.textContent='Blocked players';panel.append(title);try{const result=await safety('blocks') as {blocked:{id:string;name:string}[]};if(!result.blocked.length){const p=document.createElement('p');p.textContent='No blocked players.';panel.append(p)}for(const {id,name} of result.blocked){const button=document.createElement('button');button.textContent=`Unblock ${name}`;button.onclick=()=>{button.disabled=true;void safety('block',{targetId:id,blocked:false}).then(()=>button.remove()).catch(()=>{button.textContent='Could not unblock. Try again.';button.disabled=false;});};panel.append(button)}}catch{const p=document.createElement('p');p.textContent='Blocked players are unavailable right now.';panel.append(p)}return panel;}
